# Generated by Django 3.2.5 on 2023-02-25 19:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('symbol', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=20)),
                ('volume', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=20)),
                ('dominance', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
