# Generated by Django 3.2.5 on 2023-03-10 23:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical',
            name='volume_divided_market',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=20),
        ),
    ]
